# Use an official Ubuntu base image
FROM ubuntu:22.04

# Set environment variables to avoid interactive prompts during installation
ENV DEBIAN_FRONTEND=noninteractive
ENV SSH_USERNAME=ansible
ENV PASSWORD=ansible
ENV AUTHORIZED_KEYS="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDN4AMaM+vEpVgjTNzDx+9XItAG3MZ+4SgDYf7ySCUfg9osnnb7QqWxMW2YJyNr5WgK4B3PkPt+K37vuUkurHEDYlT+SwoT9wRMjThxKk59mXxI4wsTlcP8XE8RCnk9daunShYacP1ZX598tubcP45cmYEynGBx6D5Ztf1g0pH2xTIj9hnexDJgedWhavTxBIQqOXvdtd9/WSLryKVqmKgJxUVnrbIcT2r4WvGqJiFTqx27Q8W8Fu3KPxQk486h7vJa4FYVzMCVl+4gTyZshDgBkEJKn6cJRFi4J46hZLNi3T5tzS0dto8JaWfgd02xXK642qJ3fbVPDch4nNZxlFRd rsa-key-20240403"
# Install OpenSSH server and clean up
RUN apt -y update \
    && apt-get update -y\
    && apt -y install ansible-core\
    && apt-get install -y openssh-server iputils-ping telnet iproute2 nano sudo systemctl\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN ssh-keygen -A
RUN echo "ansible   ALL=(ALL:ALL) ALL" >> /etc/sudoers

# Create the privilege separation directory and fix permissions
RUN mkdir -p /run/sshd \
    && chmod 755 /run/sshd

# Expose SSH port
EXPOSE 22

# Create the non-root user with the ability to set a password and authorized keys using environment variables
RUN useradd -ms /bin/bash $SSH_USERNAME

# Set up SSH configuration
RUN mkdir -p /home/$SSH_USERNAME/.ssh && chown $SSH_USERNAME:$SSH_USERNAME /home/$SSH_USERNAME/.ssh \
    && echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config \
    && echo "PermitRootLogin no" >> /etc/ssh/sshd_config

# Copy the script to configure the user's password and authorized keys
COPY configure-ssh-user.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/configure-ssh-user.sh
RUN echo "ansible:ansible" | chpasswd
# Start SSH server
CMD ["/usr/local/bin/configure-ssh-user.sh"]
